//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::TextEdit::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class TextEdit::MainPage::MainPage_obj6_Bindings 
    : public ::XamlBindingInfo::XamlBindingsBase<::TextEdit::Phone>
{
public:
    MainPage_obj6_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 9:
                this->obj9 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 10:
                this->obj10 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 11:
                this->obj11 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 12:
                this->obj12 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 13:
                this->obj13 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 14:
                this->obj14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 15:
                this->obj15 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
        }
    }

    void ResetTemplate()
    {
    }

    int ProcessBindings(::Windows::UI::Xaml::Controls::ContainerContentChangingEventArgs^ args)
    {
        int nextPhase = -1;
        switch(args->Phase)
        {
            case 0:
                nextPhase = -1;
                this->SetDataRoot(static_cast<::TextEdit::Phone^>(args->Item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    safe_cast<::Windows::UI::Xaml::FrameworkElement^>(args->ItemContainer->ContentTemplateRoot)->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
        }
        this->Update_((::TextEdit::Phone^) args->Item, (1 << args->Phase));
        return nextPhase;
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::TextBlock^ obj9;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj10;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj11;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj12;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj13;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj14;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj15;

    // Update methods for each path node used in binding steps.
    void Update_(::TextEdit::Phone^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_price(obj->price, phase);
                this->Update_countOfCards(obj->countOfCards, phase);
                this->Update_modelYear(obj->modelYear, phase);
                this->Update_typeOfNetwork(obj->typeOfNetwork, phase);
                this->Update_formFactor(obj->formFactor, phase);
                this->Update_producer(obj->producer, phase);
                this->Update_model(obj->model, phase);
            }
        }
    }
    void Update_price(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj9, obj, nullptr);
        }
    }
    void Update_countOfCards(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj10, obj, nullptr);
        }
    }
    void Update_modelYear(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj11, obj, nullptr);
        }
    }
    void Update_typeOfNetwork(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj12, obj, nullptr);
        }
    }
    void Update_formFactor(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj13, obj, nullptr);
        }
    }
    void Update_producer(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj14, obj, nullptr);
        }
    }
    void Update_model(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj15, obj, nullptr);
        }
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class TextEdit::MainPage::MainPage_obj1_Bindings 
    : public ::XamlBindingInfo::XamlBindingsBase<::TextEdit::MainPage>
{
public:
    MainPage_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 5:
                this->obj5 = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
                break;
        }
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::ListView^ obj5;

    // Update methods for each path node used in binding steps.
    void Update_(::TextEdit::MainPage^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_Phones(obj->Phones, phase);
            }
        }
    }
    void Update_Phones(::Windows::Foundation::Collections::IVector<::TextEdit::Phone^>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(this->obj5, obj, nullptr);
        }
    }
};

void ::TextEdit::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 2:
            {
                this->SaveBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->SaveBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::SaveBtn_Click);
            }
            break;
        case 3:
            {
                this->OpenBtn = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->OpenBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::OpenBtn_Click);
            }
            break;
        case 4:
            {
                this->ActionButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ActionButton))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Button_PointerEntered);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ActionButton))->PointerExited += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&MainPage::Button_PointerExited);
            }
            break;
        case 5:
            {
                this->PhonesView = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
            }
            break;
        case 6:
            {
                ::Windows::UI::Xaml::Controls::Grid^ element6 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(element6))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&MainPage::Grid_RightTapped);
            }
            break;
        case 7:
            {
                ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element7 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::EditButton_Click);
            }
            break;
        case 8:
            {
                ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element8 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element8))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::TextEdit::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::DeleteButton_Click);
            }
            break;
        case 16:
            {
                this->YearTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 17:
            {
                this->Cards = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 18:
            {
                this->Network = safe_cast<::Windows::UI::Xaml::Controls::AutoSuggestBox^>(__target);
            }
            break;
        case 19:
            {
                this->FormFactor = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            }
            break;
        case 20:
            {
                this->PriceTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 21:
            {
                this->ProducerTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 22:
            {
                this->ModelTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::TextEdit::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
                MainPage_obj1_Bindings* objBindings = new MainPage_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
        case 6:
            {
                ::Windows::UI::Xaml::Controls::Grid^ element6 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                MainPage_obj6_Bindings* objBindings = new MainPage_obj6_Bindings();
                objBindings->SetDataRoot(element6->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element6);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element6, bindings);
            }
            break;
    }
    return bindings;
}


